# FFNx Vibration Engine config file - FF8 Battle module

### HOW TO: ###################################################################
# Sections may be commented by default with an initial # character.
# Remove the initial # character to set the entire sections block and its flags
# -----------------------------------------------------------------------------
# Syntax:
# [ID]
# flag = value
# another_flag = value
###############################################################################

### SUPPORTED FLAGS: ##########################################################
# left_motor: An array of arrays, where each tuple MUST contain the relative
# values. This vibration values will impact the LEFT motor of the gamepad.
# The first value of the tuple is the motor force, the second value is the
# number of frames to repeat this force.
# -----------------------------------------------------------------------------
# right_motor: An array of arrays, where each tuple MUST contain the relative
# values. This vibration values will impact the RIGHT motor of the gamepad.
# The first value of the tuple is the motor force, the second value is the
# number of frames to repeat this force.
###############################################################################

# These entries will define LEFT and RIGHT motor forces for a set of
# scenes setX.
# setX: A scene ID where X is set between 0 to 63.
# -----------------------------------------------------------------------------

[set2]
left_motor = [
	[0x40, 0],
	[0x39, 1]
]
right_motor = [
	[0x40, 1],
	[0x40, 0]
]

[set3]
left_motor = [
	[0x78, 0],
	[0x78, 3],
	[0x50, 0],
	[0x01, 0]
]
right_motor = [
	[0x60, 0],
	[0x6B, 0],
	[0x6B, 2]
]

[set4]
left_motor = [
	[0x2F, 14],
	[0x0A, 14],
	[0x1E, 13],
	[0x0C, 15],
	[0x1E, 14],
	[0x0C, 14],
	[0x1E, 14],
	[0x0C, 14],
	[0x1E, 29],
	[0x0D, 14],
	[0x1F, 12],
	[0x10, 10],
	[0x20, 46],
	[0x0C, 6],
	[0x40, 2],
	[0x40, 12],
	[0x10, 0],
	[0x37, 16],
	[0x20, 0],
	[0x40, 14],
	[0x28, 7],
	[0x4A, 12],
	[0x51, 7],
	[0x2F, 9],
	[0x18, 31],
	[0x00, 22],
	[0x41, 5],
	[0x10, 24],
	[0x48, 9],
	[0x23, 23],
	[0x55, 6],
	[0x2E, 19],
	[0x63, 15],
	[0x5A, 18],
	[0x42, 15],
	[0x1C, 27]
]
right_motor = [
]

[set7]
left_motor = [
	[0x00, 14],
	[0x00, 0],
	[0x38, 1],
	[0x38, 1],
	[0x00, 1],
	[0x00, 2],
	[0x38, 1],
	[0x38, 4],
	[0x11, 5],
	[0x00, 0],
	[0x40, 0],
	[0x40, 0],
	[0x00, 1],
	[0x00, 0],
	[0x40, 1],
	[0x40, 7],
	[0x00, 31],
	[0x00, 4],
	[0x45, 1],
	[0x3C, 3],
	[0x45, 1],
	[0x40, 11],
	[0x29, 8],
	[0x08, 3]
]
right_motor = [
]

[set11]
left_motor = [
	[0x20, 4],
	[0x3F, 24],
	[0x20, 0],
	[0x00, 23],
	[0x3C, 4],
	[0x28, 0]
]
right_motor = [
]
