# FFNx Vibration Engine config file - FF8 Field module

### HOW TO: ###################################################################
# Sections may be commented by default with an initial # character.
# Remove the initial # character to set the entire sections block and its flags
# -----------------------------------------------------------------------------
# Syntax:
# [ID]
# flag = value
# another_flag = value
###############################################################################

### SUPPORTED FLAGS: ##########################################################
# left_motor: An array of arrays, where each tuple MUST contain the relative
# values. This vibration values will impact the LEFT motor of the gamepad.
# The first value of the tuple is the motor force, the second value is the
# number of frames to repeat this force.
# -----------------------------------------------------------------------------
# right_motor: An array of arrays, where each tuple MUST contain the relative
# values. This vibration values will impact the RIGHT motor of the gamepad.
# The first value of the tuple is the motor force, the second value is the
# number of frames to repeat this force.
###############################################################################

# These entries will define LEFT and RIGHT motor forces for a set of
# scenes setX.
# setX: A scene ID where X is set between 0 to 63.
# -----------------------------------------------------------------------------

[set0]
left_motor = [
	[0x60, 0],
	[0x60, 0],
	[0x5C, 3],
	[0x42, 6],
	[0x18, 17]
]
right_motor = [
	[0x00, 29]
]

[set1]
left_motor = [
	[0x50, 0],
	[0x50, 12]
]
right_motor = [
	[0x40, 0],
	[0x40, 0],
	[0x00, 11]
]

[set2]
left_motor = [
	[0x41, 16]
]
right_motor = [
	[0x00, 10]
]

[set3]
left_motor = [
	[0x60, 0],
	[0x60, 1],
	[0x41, 0],
	[0x50, 0],
	[0x50, 39],
	[0x01, 0]
]
right_motor = [
	[0x00, 44]
]

[set4]
left_motor = [
	[0x59, 0],
	[0x59, 0],
	[0x45, 0],
	[0x41, 0],
	[0x50, 0],
	[0x50, 14]
]
right_motor = [
	[0x00, 19]
]

[set5]
left_motor = [
	[0x5F, 0],
	[0x5F, 0],
	[0x40, 0],
	[0x57, 2],
	[0x40, 0],
	[0x50, 3],
	[0x30, 0],
	[0x46, 34]
]
right_motor = [
	[0x00, 45]
]

[set6]
left_motor = [
	[0x50, 0],
	[0x50, 0],
	[0x30, 0],
	[0x30, 0],
	[0x50, 0],
	[0x50, 0],
	[0x30, 0],
	[0x30, 0],
	[0x50, 0],
	[0x50, 0],
	[0x30, 0],
	[0x30, 0],
	[0x50, 0],
	[0x50, 0],
	[0x30, 0],
	[0x30, 0],
	[0x50, 0],
	[0x50, 8],
	[0x23, 18]
]
right_motor = [
	[0x00, 44]
]

[set7]
left_motor = [
	[0x41, 0],
	[0x48, 0],
	[0x4F, 0],
	[0x55, 7]
]
right_motor = [
	[0x00, 10]
]

[set8]
left_motor = [
	[0x42, 3],
	[0x54, 0],
	[0x3C, 0],
	[0x48, 2],
	[0x54, 0],
	[0x43, 4],
	[0x50, 0],
	[0x40, 0],
	[0x3B, 0],
	[0x35, 0],
	[0x32, 0],
	[0x30, 0],
	[0x2C, 0],
	[0x2E, 0],
	[0x30, 0],
	[0x34, 0],
	[0x36, 0],
	[0x3A, 0],
	[0x30, 0],
	[0x32, 0],
	[0x35, 0],
	[0x3A, 0],
	[0x31, 0],
	[0x31, 0],
	[0x60, 0],
	[0x60, 0],
	[0x5A, 0],
	[0x52, 0],
	[0x47, 0],
	[0x40, 0],
	[0x40, 0],
	[0x60, 0],
	[0x60, 0],
	[0x5C, 0],
	[0x5C, 0],
	[0x5C, 0],
	[0x59, 45]
]
right_motor = [
	[0x00, 33],
	[0x00, 0],
	[0x40, 0],
	[0x40, 0],
	[0x00, 4],
	[0x00, 0],
	[0x40, 0],
	[0x40, 0],
	[0x00, 0],
	[0x40, 0],
	[0x40, 0],
	[0x31, 41]
]

[set9]
left_motor = [
	[0x59, 1],
	[0x53, 10]
]
right_motor = [
	[0x00, 0],
	[0x50, 0],
	[0x00, 10]
]

[set10]
left_motor = [
	[0x49, 1],
	[0x44, 0],
	[0x25, 0],
	[0x23, 0],
	[0x31, 0],
	[0x2E, 6]
]
right_motor = [
	[0x00, 0],
	[0x40, 0],
	[0x00, 10]
]

[set11]
left_motor = [
	[0x48, 1],
	[0x48, 0]
]
right_motor = [
	[0x00, 0],
	[0x48, 0]
]

[set12]
left_motor = [
	[0x5F, 1],
	[0x5F, 0],
	[0x50, 0],
	[0x50, 0],
	[0x5F, 3],
	[0x5F, 66]
]
right_motor = [
	[0x40, 0],
	[0x40, 10],
	[0x00, 63]
]

[set13]
left_motor = [
	[0x50, 1],
	[0x50, 0],
	[0x30, 0],
	[0x30, 0],
	[0x47, 0],
	[0x45, 0],
	[0x3B, 0],
	[0x34, 0],
	[0x30, 0],
	[0x38, 0],
	[0x41, 0],
	[0x46, 0],
	[0x4D, 0],
	[0x48, 0],
	[0x44, 0],
	[0x2F, 0],
	[0x3B, 2],
	[0x54, 0],
	[0x54, 3],
	[0x32, 0],
	[0x34, 0],
	[0x46, 6],
	[0x40, 1],
	[0x3C, 54]
]
right_motor = [
	[0x00, 90]
]

[set14]
left_motor = [
	[0x60, 1],
	[0x5F, 0],
	[0x4E, 3],
	[0x40, 0],
	[0x4C, 11],
	[0x2B, 0],
	[0x23, 34]
]
right_motor = [
	[0x00, 55]
]

[set15]
left_motor = [
	[0x00, 1]
]
right_motor = [
	[0x60, 0],
	[0x60, 0],
	[0x01, 0]
]

[set16]
left_motor = [
	[0x4F, 1],
	[0x48, 0],
	[0x31, 0],
	[0x31, 2],
	[0x60, 0],
	[0x60, 0],
	[0x4C, 4],
	[0x40, 0],
	[0x4F, 1],
	[0x4B, 0],
	[0x3F, 0],
	[0x3F, 87]
]
right_motor = [
	[0x00, 105]
]

[set17]
left_motor = [
	[0x51, 2],
	[0x51, 0],
	[0x40, 1],
	[0x55, 0],
	[0x30, 0],
	[0x52, 1],
	[0x2F, 0],
	[0x55, 0],
	[0x4C, 0],
	[0x35, 1],
	[0x53, 2],
	[0x3F, 0],
	[0x49, 3],
	[0x3D, 0],
	[0x4B, 4],
	[0x38, 0],
	[0x46, 22]
]
right_motor = [
	[0x00, 52]
]

[set18]
left_motor = [
	[0x2F, 0],
	[0x58, 0],
	[0x5F, 0],
	[0x60, 0],
	[0x41, 0],
	[0x41, 0],
	[0x53, 0],
	[0x50, 0],
	[0x4A, 0],
	[0x3F, 0],
	[0x24, 0],
	[0x26, 0],
	[0x4A, 0],
	[0x45, 3],
	[0x20, 0],
	[0x29, 0],
	[0x46, 0],
	[0x40, 0],
	[0x40, 0],
	[0x2C, 0],
	[0x28, 0],
	[0x24, 0],
	[0x3F, 0],
	[0x40, 0],
	[0x35, 27]
]
right_motor = [
	[0x00, 54]
]

[set19]
left_motor = [
	[0x50, 0],
	[0x50, 0],
	[0x4C, 0],
	[0x40, 0],
	[0x40, 0],
	[0x48, 0],
	[0x48, 0],
	[0x40, 0],
	[0x40, 21]
]
right_motor = [
	[0x00, 29]
]

[set20]
left_motor = [
	[0x23, 9],
	[0x56, 0],
	[0x55, 0],
	[0x54, 0],
	[0x53, 0],
	[0x3E, 0],
	[0x3D, 0],
	[0x51, 6],
	[0x43, 8],
	[0x25, 0],
	[0x41, 0],
	[0x40, 20]
]
right_motor = [
	[0x00, 31],
	[0x00, 0],
	[0x40, 0],
	[0x40, 5],
	[0x00, 14]
]

[set21]
left_motor = [
	[0x5F, 1],
	[0x5F, 0],
	[0x52, 1],
	[0x4B, 6],
	[0x30, 7],
	[0x19, 11]
]
right_motor = [
	[0x00, 31]
]

[set22]
left_motor = [
	[0x60, 0],
	[0x60, 0],
	[0x52, 0],
	[0x40, 0],
	[0x3C, 0],
	[0x2B, 8]
]
right_motor = [
	[0x5C, 2],
	[0x00, 10]
]

[set23]
left_motor = [
	[0x61, 0],
	[0x60, 0],
	[0x31, 0],
	[0x3A, 0],
	[0x55, 0],
	[0x56, 0],
	[0x30, 0],
	[0x39, 0],
	[0x60, 0],
	[0x60, 0],
	[0x30, 0],
	[0x38, 0],
	[0x54, 0],
	[0x55, 0],
	[0x2F, 0],
	[0x3C, 0],
	[0x5C, 0],
	[0x5D, 0],
	[0x30, 0],
	[0x3C, 0],
	[0x51, 0],
	[0x53, 0],
	[0x3B, 23]
]
right_motor = [
	[0x00, 45]
]

[set24]
left_motor = [
	[0x40, 0],
	[0x40, 0],
	[0x20, 0],
	[0x40, 0],
	[0x40, 0],
	[0x20, 0],
	[0x40, 0],
	[0x40, 0],
	[0x20, 0],
	[0x40, 0],
	[0x40, 0],
	[0x20, 0],
	[0x40, 0],
	[0x40, 0],
	[0x34, 0],
	[0x2C, 8]
]
right_motor = [
	[0x40, 0],
	[0x00, 0],
	[0x40, 0],
	[0x00, 0],
	[0x40, 0],
	[0x00, 0],
	[0x40, 0],
	[0x00, 0],
	[0x40, 0],
	[0x00, 0],
	[0x40, 0],
	[0x00, 0],
	[0x40, 0],
	[0x00, 0],
	[0x41, 0],
	[0x00, 8]
]

[set25]
left_motor = [
	[0x61, 0],
	[0x60, 1],
	[0x50, 0],
	[0x57, 0],
	[0x55, 0],
	[0x46, 0],
	[0x40, 0],
	[0x52, 0],
	[0x4F, 0],
	[0x42, 0],
	[0x3F, 0],
	[0x4E, 0],
	[0x4D, 47]
]
right_motor = [
	[0x00, 60]
]

[set26]
left_motor = [
	[0x60, 29]
]
right_motor = [
	[0x00, 29]
]

[set27]
left_motor = [
	[0x00, 23]
]
right_motor = [
	[0x40, 9],
	[0x40, 13]
]

[set28]
left_motor = [
	[0x40, 1],
	[0x40, 0],
	[0x00, 0],
	[0x00, 0],
	[0x60, 1],
	[0x60, 0]
]
right_motor = [
	[0x00, 7]
]

[set29]
left_motor = [
	[0x40, 1],
	[0x40, 0],
	[0x00, 0],
	[0x00, 0],
	[0x5F, 1],
	[0x5F, 0]
]
right_motor = [
	[0x00, 1],
	[0x00, 0],
	[0x40, 0],
	[0x40, 0],
	[0x00, 2]
]

[set30]
left_motor = [
	[0x5F, 0],
	[0x5F, 0],
	[0x50, 0],
	[0x3F, 0],
	[0x34, 0],
	[0x29, 0],
	[0x24, 3],
	[0x24, 0],
	[0x30, 0],
	[0x38, 0],
	[0x48, 0],
	[0x52, 0],
	[0x5B, 0],
	[0x60, 14]
]
right_motor = [
	[0x00, 30]
]

[set31]
left_motor = [
	[0x5F, 0],
	[0x53, 0],
	[0x48, 0],
	[0x3C, 0],
	[0x34, 0],
	[0x28, 0],
	[0x24, 3],
	[0x24, 0],
	[0x2B, 0],
	[0x35, 0],
	[0x40, 0],
	[0x4C, 0],
	[0x58, 0],
	[0x5F, 14]
]
right_motor = [
	[0x40, 2],
	[0x40, 0],
	[0x30, 7],
	[0x30, 0],
	[0x40, 2],
	[0x40, 13]
]

[set32]
left_motor = [
	[0x60, 0],
	[0x60, 0],
	[0x30, 0],
	[0x55, 0],
	[0x55, 0],
	[0x30, 0],
	[0x5B, 0],
	[0x5B, 0],
	[0x40, 0],
	[0x50, 0],
	[0x50, 34]
]
right_motor = [
	[0x00, 44]
]

[set33]
left_motor = [
	[0x60, 0],
	[0x60, 0],
	[0x59, 3],
	[0x2C, 15]
]
right_motor = [
	[0x00, 21]
]

[set34]
left_motor = [
	[0x50, 2],
	[0x47, 0],
	[0x4F, 2],
	[0x3F, 0],
	[0x48, 3],
	[0x33, 0],
	[0x38, 3],
	[0x29, 0],
	[0x30, 16]
]
right_motor = [
	[0x00, 34]
]

[set35]
left_motor = [
	[0x61, 0],
	[0x56, 0],
	[0x55, 0],
	[0x49, 0],
	[0x48, 26]
]
right_motor = [
	[0x00, 29]
]

[set36]
left_motor = [
	[0x41, 0],
	[0x41, 0],
	[0x60, 0],
	[0x60, 0]
]
right_motor = [
	[0x50, 0],
	[0x50, 0],
	[0x00, 1]
]

[set37]
left_motor = [
	[0x5F, 0],
	[0x5E, 0],
	[0x00, 0],
	[0x00, 0],
	[0x43, 0],
	[0x38, 0]
]
right_motor = [
	[0x50, 0],
	[0x40, 0],
	[0x00, 3]
]

[set38]
left_motor = [
	[0x58, 0],
	[0x58, 0],
	[0x44, 0],
	[0x44, 0],
	[0x50, 0],
	[0x50, 0],
	[0x38, 0],
	[0x38, 22]
]
right_motor = [
	[0x00, 29]
]

[set39]
left_motor = [
	[0x57, 1],
	[0x52, 0],
	[0x36, 0],
	[0x35, 0],
	[0x44, 0],
	[0x3D, 0],
	[0x31, 0],
	[0x2B, 10],
	[0x03, 0]
]
right_motor = [
	[0x00, 18]
]

[set40]
left_motor = [
	[0x34, 13],
	[0x1A, 0],
	[0x3F, 7],
	[0x23, 11],
	[0x1C, 0],
	[0x40, 20],
	[0x1C, 0],
	[0x3E, 12],
	[0x1B, 0],
	[0x3A, 13],
	[0x1A, 0],
	[0x3A, 23],
	[0x1F, 0],
	[0x3A, 25]
]
right_motor = [
	[0x00, 137]
]

[set41]
left_motor = [
	[0x2F, 14],
	[0x10, 239],
	[0x38, 44],
	[0x40, 14]
]
right_motor = [
	[0x00, 239],
	[0x00, 74]
]

[set42]
left_motor = [
	[0x68, 0],
	[0x68, 0],
	[0x68, 0],
	[0x67, 7],
	[0x35, 2],
	[0x2B, 6],
	[0x34, 7],
	[0x2A, 7],
	[0x33, 13],
	[0x28, 99]
]
right_motor = [
	[0x50, 1],
	[0x50, 7],
	[0x00, 140]
]

[set43]
left_motor = [
	[0x33, 0],
	[0x38, 0],
	[0x3C, 0],
	[0x40, 0],
	[0x43, 0],
	[0x49, 0],
	[0x52, 0],
	[0x5A, 0],
	[0x5F, 0],
	[0x5F, 0],
	[0x59, 0],
	[0x52, 4],
	[0x38, 4],
	[0x30, 4],
	[0x38, 0],
	[0x3E, 0],
	[0x43, 0],
	[0x48, 0],
	[0x49, 0],
	[0x47, 0],
	[0x43, 0],
	[0x3E, 0],
	[0x37, 0],
	[0x34, 0],
	[0x30, 0],
	[0x30, 2],
	[0x3C, 0],
	[0x43, 0],
	[0x44, 0],
	[0x3E, 0],
	[0x30, 29],
	[0x21, 0],
	[0x1E, 0],
	[0x18, 0],
	[0x16, 0],
	[0x1A, 0],
	[0x20, 0],
	[0x2A, 0],
	[0x31, 0],
	[0x37, 0],
	[0x3C, 0],
	[0x41, 0],
	[0x45, 0],
	[0x46, 0],
	[0x46, 0],
	[0x44, 0],
	[0x42, 0],
	[0x40, 0],
	[0x3A, 0],
	[0x2F, 0],
	[0x22, 0],
	[0x21, 0],
	[0x27, 0],
	[0x34, 0],
	[0x3E, 0],
	[0x45, 0],
	[0x46, 0],
	[0x47, 0],
	[0x45, 0],
	[0x3E, 0],
	[0x32, 0],
	[0x2B, 0],
	[0x22, 0],
	[0x24, 0],
	[0x2A, 4],
	[0x48, 0],
	[0x4C, 0],
	[0x4F, 2],
	[0x4F, 8],
	[0x27, 0],
	[0x23, 0],
	[0x26, 5],
	[0x5D, 3],
	[0x5E, 4],
	[0x31, 0],
	[0x36, 0],
	[0x3B, 0],
	[0x3B, 0],
	[0x35, 0],
	[0x2B, 0],
	[0x26, 0],
	[0x21, 0],
	[0x20, 0],
	[0x21, 0],
	[0x23, 0],
	[0x28, 0],
	[0x31, 0],
	[0x42, 0],
	[0x49, 0],
	[0x49, 0],
	[0x45, 0],
	[0x40, 0],
	[0x37, 0],
	[0x2D, 0],
	[0x25, 0],
	[0x25, 0],
	[0x25, 0],
	[0x28, 0],
	[0x2F, 0],
	[0x35, 2],
	[0x36, 0],
	[0x33, 0],
	[0x2C, 0],
	[0x26, 0],
	[0x23, 0],
	[0x22, 0],
	[0x20, 0],
	[0x21, 0],
	[0x24, 0],
	[0x2A, 0],
	[0x31, 0],
	[0x36, 3],
	[0x36, 0],
	[0x31, 0],
	[0x2A, 0],
	[0x26, 0],
	[0x22, 0],
	[0x23, 0],
	[0x27, 0],
	[0x2C, 0],
	[0x31, 0],
	[0x35, 2],
	[0x35, 0],
	[0x32, 0],
	[0x2C, 0],
	[0x24, 0],
	[0x20, 0],
	[0x22, 0],
	[0x27, 0],
	[0x2F, 0],
	[0x32, 2],
	[0x32, 0],
	[0x30, 4],
	[0x21, 24],
	[0x01, 0]
]
right_motor = [
	[0x00, 239]
]

[set44]
left_motor = [
	[0x50, 0],
	[0x54, 0],
	[0x50, 2],
	[0x30, 5],
	[0x1F, 0],
	[0x1F, 7],
	[0x31, 0],
	[0x40, 0],
	[0x44, 0],
	[0x40, 2],
	[0x30, 5],
	[0x20, 0],
	[0x20, 7],
	[0x30, 0],
	[0x38, 0],
	[0x3D, 0],
	[0x38, 2],
	[0x31, 5],
	[0x20, 0],
	[0x20, 6],
	[0x29, 0],
	[0x2D, 0],
	[0x30, 0],
	[0x2B, 3],
	[0x1C, 51]
]
right_motor = [
	[0x00, 119]
]

[set45]
left_motor = [
	[0x30, 20],
	[0x1F, 18],
	[0x2E, 21],
	[0x14, 24],
	[0x2D, 33]
]
right_motor = [
	[0x00, 120]
]
